### PR TITLE
Fix bugs in cell suppression calculation

### LINKED ISSUE #17: Incorrect cell suppression with specific example
Hope all is going well with you with your recent movements! I will attempt to tackle this one - it appears that the cell suppression algorithm has some instances where it doesn't appear to be suppressing all possible backwards calculations. I have included an example below, with variables recoded and Ns shifted bidirectionally while still maintaining the core relationships that are triggering the bug. 

``` r
devtools::load_all(".")
#> ℹ Loading modulartabler
  
  compactform <- structure(list(
    `Factor1` = structure(c(1L, 1L, 1L, 2L, 2L, 2L, 3L, 3L, 
                            3L, 4L, 4L, 4L, 5L, 5L, 5L, 6L, 6L, 6L,
                            7L, 7L, 7L, 8L, 8L, 8L, 9L, 9L, 9L),
                          levels = c("Lvl1", "Lvl2", "Lvl3", "Lvl4", 
                                     "Lvl5", "Lvl6", "Lvl7", "Lvl8", 
                                     "Total"), class = "factor"),
    `Factor2` = structure(c(1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 
                            2L, 3L, 1L, 2L, 3L, 1L, 2L,
                            3L, 1L, 2L, 3L, 1L, 2L, 3L, 1L, 2L, 3L), 
                          levels = c("Level1", "Level2", "Total"), 
                          class = "factor"),
    n = c(262L, 78L, 340L, 110L, 59L, 169L, 52L, 16L, 68L, 54L, 16L, 
          70L, 97L, 17L, 114L, 90L, 37L, 127L, 1L, 3L, 4L, 0L, 0L, 
          0L, 666L, 226L, 892L)),
    row.names = c(NA, -27L), class = c("tbl_df", "tbl", "data.frame"))
  
  Fct1Map <- RangeMappingTable$new(
    "Factor1", "fct1",
    "Lvl1" = c(-Inf, 1),
    "Lvl2" = c(1, 3),
    "Lvl3" = c(3, 5),
    "Lvl4" = c(5, 7),
    "Lvl5" = c(7, 9),
    "Lvl6" = c(9, 11),
    "Lvl7" = c(11, Inf),
    .other = "Lvl8",
    .total = "Total"
  )
  
  Fct2Map <- BaseMappingTable$new(
    tibble::tibble(fct2 = rep(1:2, 2),
                   Factor2 = forcats::as_factor(c("Level1", "Level2", rep("Total", 2)))),
    "fct2", "Factor2"
  )
  
  MMap <- MultiMappingTable$new(Fct1Map, Fct2Map)
  
  test_suppress <- compactform %>%
    dplyr::mutate(suppress = determine_cell_suppression(n, MMap$nullspace))
  
  convert_tabular(test_suppress, Factor1 ~ Factor2 + .Measure, 
                  measures = c(No. = "n", S = "suppress"))
#> # A tibble: 9 × 7
#>   Factor1 Level1_No. Level1_S Level2_No. Level2_S Total_No. Total_S
#>   <fct>        <int> <lgl>         <int> <lgl>        <int> <lgl>  
#> 1 Lvl1           262 FALSE            78 FALSE          340 FALSE  
#> 2 Lvl2           110 FALSE            59 FALSE          169 FALSE  
#> 3 Lvl3            52 TRUE             16 FALSE           68 TRUE   
#> 4 Lvl4            54 FALSE            16 FALSE           70 FALSE  
#> 5 Lvl5            97 FALSE            17 FALSE          114 FALSE  
#> 6 Lvl6            90 FALSE            37 FALSE          127 FALSE  
#> 7 Lvl7             1 TRUE              3 TRUE             4 TRUE   
#> 8 Lvl8             0 FALSE             0 FALSE            0 FALSE  
#> 9 Total          666 FALSE           226 FALSE          892 FALSE
  
  # For messing around with numbers
  raw_data <- compactform %>%
    dplyr::filter(dplyr::if_all(c(Factor1, Factor2), ~ .x != "Total")) %>%
    tidyr::uncount(weights = n)
```

<sup>Created on 2024-09-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

As you can see for the Level2 column, only one value has been suppressed so the Lvl7 row can be recalculated off this total. I have some theories for what is triggering this but will delve into this further.

### PR DESCRIPTION
**Pull request by PeterM74**
Resolves #17 
No rush on reviewing!

## Changes
* `suppress_secondary()` now considers and adds constraints for each primary suppression cell in `ik` across the three subproblems in isolation *before* solving the master LP. Fixed a rare issue where a cell (x<sub>1</sub>) in `ik` would create a suppression pattern that coincidentally covered a future `ik` cell (x<sub>2</sub>) but future constraints from further `ik` cells (x<sub>3</sub>) would leave x<sub>2</sub> vulnerable as it wasn't explicitly added as a constraint.
* In rare cases of large tables, the `HiGHS` solver will return floating point numbers rather than binary integers 0/1. Since `as.logical()` turns any non-zero number into `TRUE`, this resulted in excessive suppression patterns in certain tables. This has been changed into `solution >= 0.5` to split the floating point numbers into a logical vector. I picked 0.5 as the mid-point but to be honest, the floating points returned were at the extremes of the binary space so I'm not concerned about precision of floating point numbers around this 0.5 cutoff.
* The above two issues have been added as a unit test in `test-cell_suppression` to prevent regression.
* Minor updates to errors returned and documentation for the cell suppression functions

## Benchmarking
Benchmarking returns relatively equivalent results (acknowledging that due to the algorithm change there will always be equal or more constraints added and more `max_iter` loops).

```
   algo  version                        `median (s)` Cumulative_mem  n_gc
   <chr> <chr>                                 <dbl>      <bch:byt> <dbl>
 1 Old   Maps: 2, items: 10, version: 1        0.505        68.99MB   141
 2 Old   Maps: 2, items: 10, version: 2        0.492        64.28MB   115
 3 Old   Maps: 2, items: 10, version: 3        0.482        60.71MB   115
 4 Old   Maps: 3, items: 5, version: 1         7.11        973.67MB   994
 5 Old   Maps: 3, items: 5, version: 2         8.90        824.64MB   823
 6 Old   Maps: 3, items: 5, version: 3         9.73        973.57MB   986
-------------------------------------------------------------------------
13 New   Maps: 2, items: 10, version: 1        0.747       117.16MB   184
14 New   Maps: 2, items: 10, version: 2        0.489        72.15MB   104
15 New   Maps: 2, items: 10, version: 3        0.618        90.14MB   131
16 New   Maps: 3, items: 5, version: 1         4.29          1.19GB  1144
17 New   Maps: 3, items: 5, version: 2         7.84          1.77GB  1703
18 New   Maps: 3, items: 5, version: 3         5.51          1.44GB  1398
```

## Checking
I have manually reviewed 40 randomly generated tables to ensure there are no further issues (this check is what found bullet point 2 above). While I can't guarantee they are the most optimal tables from my review, I couldn't detect any egregious issues with the suppression patterns returned. Below is the code I used if you wish to test yourself:

```
devtools::load_all()

f <- function(colname, max = 5) {
  BaseMappingTable$new(tibble::tibble(!!colname := c(letters[1:max],
                                                     letters[1:max]),
                                      !!paste0(colname, "2") := c(LETTERS[1:max],
                                                                  rep("Total", max))),
                       colname, paste0(colname, "2"))
}

generate_aggregate <- function(seed, dimtable, elements) {
  map <- do.call(MultiMappingTable$new, purrr::map(LETTERS[1:dimtable], ~ f(.x, max = elements)))

  agg <- do.call(tidyr::expand_grid, map(1:dimtable, ~ letters[1:elements])) %>%
    purrr::set_names(nm = LETTERS[1:dimtable])

  set.seed(seed)
  raw <- dplyr::mutate(agg, n = sample(0L:40L, size = elements^dimtable, replace = TRUE)) %>%
    tidyr::uncount(weights = n)

  final_agg <- map$count_aggregate(raw) %>%
    dplyr::mutate(suppress = determine_cell_suppression(n, map$nullspace, max_iter = 200))

  final_agg
}

Outputs <- purrr::pmap(list(seed = 123:162,
                            dimtable = rep(2:3, each = 20),
                            elements = rep(2:5, each = 5, times = 2)),
                       generate_aggregate)
```

## Local devtools::check()
── R CMD check results ───── modulartabler 0.1.0 ────
Duration: 31.2s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔

### CODE REVIEW

File: R/cell_suppression.R [hunk 1]
```diff
@@ -252,103 +255,114 @@ suppress_secondary <- function(
...
+    # Exit with error if iteration limit exceeded
+    if (identical(i, max_iter))
+      stop("Maximum attacker iterations reached. Consider increasing the max_iter parameter")
 
-      candidate_suppression <- as.logical(master_soln$solution)
-    }
+    # Re-solve master LP with new constraints to feed next cycle
+    i <- i + 1L
+    candidate_suppression <- as.logical(ROI_solve(master_lp, ...)$solution)
+    candidate_suppression <- ROI_solve(master_lp, ...)$solution >= 0.5
```
Comment (inpowell) [inline R/cell_suppression.R]: We should probably save the master LP solution as an object and check the status code before running with the new candidate suppression.

(Also this looks like it might be a duplicate line.)

File: R/cell_suppression.R [hunk 2]
```diff
@@ -252,103 +255,114 @@ suppress_secondary <- function(
...
+  i <- 1L
+
+  repeat {
+
+    attacker_success <- FALSE
+
+    for (attack.ik in ik) { # Attack all cells to be suppressed
+
+      # Calculate known bounds
+        if (SPL[attack.ik] > 0L || UPL[attack.ik] > 0L) {
```
Comment (inpowell) [inline R/cell_suppression.R]: I think something funny happened with the indentation here - could you please check the body of this for-loop is correctly indented? RStudio’s Ctrl-i should be sufficient.

File: tests/testthat/test-cell_suppression.R [hunk 3]
```diff
@@ -51,6 +51,69 @@ test_that("determine_cell_suppression correctly suppresses cells", {
...
+                 -1, 0, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, -1), ncol = 27)
+
+  soln <- c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE,
+            FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
+            TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE)
+
+  expect_identical(determine_cell_suppression(n, ns), soln)
+})
+
+test_that("Solves highly dimensional tables that may return non-integer LP solutions", {
```
Comment (inpowell) [inline tests/testthat/test-cell_suppression.R]: I think we want this test, but I’d prefer if we didn’t have to trust that MultiMappingTable’s ordering won’t change in future. It’s also large enough that we probably don’t want to have the matrix in code.

How about saving the expected suppression/test counts/test nullspace to a (say) tab-separated file and writing a test helper (say in tests/testthat/helper-supressions.R) to read those three things in (and maybe even write those things out). Then, it would be a touch easier to read and verify the test data.

Suggested tab file format something like desired `suppression` in first column, test `count` in second column and then rows of the nullspace in subsequent columns `NS1`, `NS2`, etc. So effectively we would write out `cbind(suppression = suppress, counts = n, NS = t(nullspace))` with something that handles matrix-columns.

**Review by inpowell — COMMENTED** [review]
Nice work! Sounds like it’s been a Herculean effort, so thank you. I’ve just added some initial comments without running the code, but everything’s looking pretty good to me.

File: R/cell_suppression.R (hunk 1 above)
Comment (PeterM74) [reply R/cell_suppression.R]: 🤦‍♂️ You are right, that is leftover from doing testing. Have deleted the `as.logical()` line. Good idea on checking status code before running new `candidate_suppression`. I have added an error that passes the message from the solver back to the user if status code != 0 as without running a new `candidate_suppression`, it will otherwise loop back and continue tripping the same subproblems until it hits `max_iter`. Would appreciate your thoughts on any situation where a non-0 status code would still be appropriate to continue solving

File: R/cell_suppression.R (hunk 2 above)
Comment (PeterM74) [reply R/cell_suppression.R]: Done! I think when deleting some of the lines, I didn't re-ident with Cntl-I

File: tests/testthat/test-cell_suppression.R (hunk 3 above)
Comment (PeterM74) [reply tests/testthat/test-cell_suppression.R]: That's a good idea! I have converted these two into .tsv files and added a helper function as you suggested. Tests passing

**Comment by PeterM74** [comment]
Just some results from further testing - applied this update to an internal fork and ran across multiple tables. 92% had the same suppression pattern, of those that didn't:

* 3 had an incorrect suppression pattern using the old algo in comparison to the new update
* 1 had a different suppression pattern but both were optimal when using the default N as the weight (there were similar numbers in cells)

This plus the 40 random tables I tested earlier has given me confidence that we are on the right track with this patch!

In other news, this package may be gaining some interest! I was mentioning it to some old colleagues who do aggregate requests and they asked for a demo, someone else overheard and has also requested to be included and now it has become a topic at a community of practice meeting across the organisation 😄 No date set yet as obviously will want this fix included before distribution (plus all the other changes before finalising v0.1)

**Review by inpowell — APPROVED** [review]
Thanks for all your work on this! I've made some changes to style for my own personal bugbears, and shifted the test data to its own subdirectory in testthat.

On the laptop I'm currently using (Windows, R 4.4.1), R CMD check passes in 45.1 seconds.

Exciting to hear the package is gaining traction!

**Comment by PeterM74** [comment]
Thanks Ian for the commits - always happy to keep the code style consistent! Will let you know how the preso goes
